### ISSUE TITLE
Get multiple properties of object

### ISSUE THREAD

**Issue by 501956430** [dengliming/redis-modules-java#37]
How does Java get multiple attributes？

```javascript
127.0.0.1:6379> json.set b . '{"name":"abcd","age":1,"type":1}'
ok
127.0.0.1:6379> json.get a
"{"name":"abcd","age":1,"type":1}"
//Get multiple properties
127.0.0.1:6379> json.get a name age
"{"age":1,"name":"abcd"}"
```

How to obtain multiple attributes? I don't see a corresponding method in the source code

<img width="1048" alt="截屏2022-01-21 18 15 00" src="https://user-images.githubusercontent.com/20204491/150509447-565c9b8e-48b3-42df-af3d-25b3ca99c353.png">

**Comment by dengliming** [comment]
`redisJSON.get(key, Map.class, new GetArgs().path("name", "age"))`

**Comment by 501956430** [comment]
thank

**Comment by 501956430** [comment]
Object serialization excludes null attributes, which will cause an exception when obtaining multiple attributes
`
User class:
private String name;
private Integer age;

redisJSON.set(key, new SetArgs().json("{\"name\":\"test\"}"))

redisJSON.get(key,User.class, new GetArgs().path("name", "age"))

`
error Exception:
`org.redisson.client.RedisException: ERR Path 'id' does not exist. channel: [id: 0xaf7d7702, L:/127.0.0.1:57296 - R:127.0.0.1/127.0.0.1:6379] command: (JSON.GET), promise: RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@62ccff0e(incomplete)], params: [a, name, age, id]

	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:370)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:198)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by dengliming** [comment]
```
127.0.0.1:6379> json.set b . '{"name":"abcd"}'
OK
127.0.0.1:6379> json.get b name age
(error) ERR Path 'age' does not exist
```
This should not be a client issue.

**Comment by 501956430** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
