### ISSUE TITLE
RediSearch - NoContent option not working with JSON doc

### ISSUE THREAD

**Issue by chenlizhao** [dengliming/redis-modules-java#59]
I use JSON document with redis search, it looks like:
key: user:10003:1000821:1024445:1
value: {"source":1,"sourceId":1024445,"id":1000821,"customerId":"1001906161","phone":"0","primaryChannelId":"10003","channelName":"山西一机游","appId":13,"appName":"游山西小程序","appType":2,"nickName":"OK？","isBind":0,"status":0,"openId":"oyhUG5rn_FwPwGKIZk8BqX4ZSvlo","birthday":"","sex":1,"idCardType":10,"passportNo":"","registrationTime":1588252808,"registry_entry":""}

but when I search with NoContent option as:
io.github.dengliming.redismodule.redisearch.search.SearchResult searchResult = rediSearch.search("*", new SearchOptions()
					.noContent());
if failed with below message:
2022-11-14 15:19:15.818 ERROR 232 --- [sson-netty-2-15] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x72ba1f99, L:/10.53.2.3:55239 - R:10.200.5.120/10.200.5.120:7004]
io.netty.handler.codec.DecoderException: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421) ~[netty-codec-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.72.Final.jar:4.1.72.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
	at io.github.dengliming.redismodule.redisearch.protocol.decoder.SearchResultDecoder.decode(SearchResultDecoder.java:58) ~[redisearch-1.0.5.jar:na]
	at io.github.dengliming.redismodule.redisearch.protocol.decoder.SearchResultDecoder.decode(SearchResultDecoder.java:31) ~[redisearch-1.0.5.jar:na]
	at org.redisson.client.protocol.decoder.ListMultiDecoder2.decode(ListMultiDecoder2.java:47) ~[redisson-3.16.6.jar:3.16.6]
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:436) ~[redisson-3.16.6.jar:3.16.6]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:392) ~[redisson-3.16.6.jar:3.16.6]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:198) ~[redisson-3.16.6.jar:3.16.6]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137) ~[redisson-3.16.6.jar:3.16.6]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113) ~[redisson-3.16.6.jar:3.16.6]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[netty-codec-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.72.Final.jar:4.1.72.Final]
	... 17 common frames omitted

but with page(0,0) option as:
io.github.dengliming.redismodule.redisearch.search.SearchResult searchResult = rediSearch.search("*", new SearchOptions()
					.page(new Page(0,0)));

it was ok then, is it a bug or not?

lizhao

**Comment by chenlizhao** [comment]
redis version: 6.2.6
redis-module-java: 2.0.2
redisearch: 2.2

**Comment by dengliming** [comment]
How do you put your json into redis?

**Comment by chenlizhao** [comment]
I use redis-py to import data into redis, python code is:

client = RedisCluster(startup_nodes=nodes, read_from_replicas=True, **REDIS_CONNECTION_PARAMS)
pipe = client.pipeline(transaction=False)
with open('redis.dat','r',encoding='utf-8') as f:
  while True:
    lines = f.readline()
    lines = lines.replace('\\','')
    s = lines.split("\t")
    value = s[1]
    key = s[0]
    pipe.json().set(key, '.', eval(value))
pipe.execute()

**Comment by dengliming** [comment]
According to the documentation https://redis.io/docs/stack/search/indexing_json/, you need to create a json index first, but we don't support this part of the api yet.

**Comment by chenlizhao** [comment]
I do create a json index at first

**Comment by dengliming** [comment]
I fixed page option not working bug just now. Can you use master version to try?

**Comment by chenlizhao** [comment]
yes, it is ok now, please close this issue

**Comment by dengliming** [comment]
Thanks. I will release a new version later.
